### ISSUE TITLE
Runaway RAM Usage on RPi

### ISSUE THREAD

**Issue by gregkinney** [kewashi/hpserver#14]
My goal is to get my Hubitat devices into my ISY. I just followed the instructions and installed HousePanel on my Hubitat, then installed the web server on my RPi. When I start the web server, the RAM usage on my RPi goes up, up, up until the RPi becomes unresponsive, after about 60 seconds. Can you please help?

**Comment by kewashi** [comment]
First - you don’t need hpserver installed to get Hubitat devices into ISY. You need the pg3hubitat node server installed on an Eist or Polish box. You can’t use rPi for that. 

The hpserver.js install does go on a rPi and is only used to get the HousePanel GUI to display devices. I do both. But note that HousePanel also displays Hubitat devices natively so strictly speaking you don’t need the pg3hubitat node server to get the GUI. 

As for your memory error, when you run hpserver pipe the output to a file and share that with me and I will try to help. Do that as 

node hpserver.js >& errors.dat &

What does error.dat look like?

**Comment by gregkinney** [comment]
Ok, let me change directions a little then. My goal is to get Hubitat devices into ISY, so I don't necessarily need HousePanel. I didn't see any instructions regarding configuration. In the PG3hubitat, it asks for "accessToken", "hubEndpt", and "restPort". Where can I find these values? I do have a Polisy which is where I installed the PG3 Hubitat node.

**Comment by gregkinney** [comment]
I thought I might have found the values for the above fields but it's still not working. Here's the log from the Hubitat PG3 node server:

> 2023-08-31 13:43:32,251 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2023-08-31 13:43:34,688 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.1.0 Starting...
2023-08-31 13:43:34,696 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2023-08-31 13:43:34,697 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db9593a10_7/./poly.py", line 5, in <module>
2023-08-31 13:43:34,699 MainThread udi_interface      ERROR    udi_interface:write: from nodes import HubitatController
2023-08-31 13:43:34,699 MainThread udi_interface      ERROR    udi_interface:write: File "/var/polyglot/pg3/ns/000db9593a10_7/nodes/HubitatController.py", line 1
2023-08-31 13:43:34,700 MainThread udi_interface      ERROR    udi_interface:write: pe == "co2sensor" ):
2023-08-31 13:43:34,701 MainThread udi_interface      ERROR    udi_interface:write: ^
2023-08-31 13:43:34,702 MainThread udi_interface      ERROR    udi_interface:write: SyntaxError
2023-08-31 13:43:34,703 MainThread udi_interface      ERROR    udi_interface:write: :
2023-08-31 13:43:34,703 MainThread udi_interface      ERROR    udi_interface:write: unmatched ')'

**Comment by kewashi** [comment]
To get ph3hubitat to work you have to install HousePanel.groovy but not all the other stuff. Open up a log page on Hubitat and re-save the groovy file. The log will show the info you need to configure pg3hubitat node server. This is all explained at https//housepanel.net

**Comment by kewashi** [comment]
Hmmmm haven’t seen that error before. Did you download the app from the node server store? The version on GitHub won’t work.

**Comment by gregkinney** [comment]
I downloaded it from the node server store.

**Comment by kewashi** [comment]
See my response to your other comment

**Comment by kewashi** [comment]
I'll close out this thread since you're now focused on pg3hubitat installation. I don't check GitHub comments often so let's move future discussions over to the UDI forum.
