### ISSUE TITLE
PG3 Hubitat Node Server not working

### ISSUE THREAD

**Issue by gregkinney** [kewashi/hpserver#15]
Here are the logs from the PG3 node server

> 2023-08-31 13:43:32,251 MainThread udi_interface INFO polylogger:set_basic_config: set_basic_config: enable=True level=30
2023-08-31 13:43:34,688 MainThread udi_interface INFO init:: UDI Python Interface for Polyglot version 3 3.1.0 Starting...
2023-08-31 13:43:34,696 MainThread udi_interface ERROR udi_interface:write: Traceback (most recent call last):
2023-08-31 13:43:34,697 MainThread udi_interface ERROR udi_interface:write: File "/var/polyglot/pg3/ns/000db9593a10_7/./poly.py", line 5, in
2023-08-31 13:43:34,699 MainThread udi_interface ERROR udi_interface:write: from nodes import HubitatController
2023-08-31 13:43:34,699 MainThread udi_interface ERROR udi_interface:write: File "/var/polyglot/pg3/ns/000db9593a10_7/nodes/HubitatController.py", line 1
2023-08-31 13:43:34,700 MainThread udi_interface ERROR udi_interface:write: pe == "co2sensor" ):
2023-08-31 13:43:34,701 MainThread udi_interface ERROR udi_interface:write: ^
2023-08-31 13:43:34,702 MainThread udi_interface ERROR udi_interface:write: SyntaxError
2023-08-31 13:43:34,703 MainThread udi_interface ERROR udi_interface:write: :
2023-08-31 13:43:34,703 MainThread udi_interface ERROR udi_interface:write: unmatched ')'

**Comment by kewashi** [comment]
It looks like the HubitatController.py file isn't getting written or launched properly. I have no idea why. The errors after the first one are all bogus. It looks like poly.py isn't even importing HubitatController properly. There is no syntax error in the source file. For example, the line

`
2023-08-31 13:43:34,700 MainThread udi_interface ERROR udi_interface:write: pe == "co2sensor" ):
`

is a subset of a line that looks like this:
`
        elif ( devtype == "co2sensor" ):
            address = "cd_" + deviceid
`
which is perfectly appropriate python syntax. So something is going amuck that is very fundamental. Are you on a Polisy or an EISY?  I've only tested on an EISY so it might be a Polisy only issue. Have you updated your PG3 installation to PG3x and the latest version? This node server requires PG3x Version 3.1.x -- I have 3.1.27

**Comment by gregkinney** [comment]
I did start a thread on UDI but didn't hear back so someone suggested that I reach out to you on git. I am on a Polisy on PG3 3.1.23. I have not updated to PG3x. So I guess that is the problem?

**Comment by kewashi** [comment]
Yea I think so. Sorry I missed seeing this on UDI. Been busy at work paying the bills you know
